--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."CLIENTS" 
   (  "CLIENT_ID" NUMBER(*,0), 
  "CITY" VARCHAR2(20 BYTE), 
  "ADDRESS" VARCHAR2(60 BYTE), 
  "COMPANY_NAME" VARCHAR2(40 BYTE), 
  "PHONE_NUMBER" VARCHAR2(13 BYTE), 
  "CONTACT_PERSON" VARCHAR2(28 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."EMPLOYEES" 
   (  "EMPLOYEE_ID" NUMBER(*,0), 
  "LAST_NAME" VARCHAR2(50 BYTE), 
  "FIRST_NAME" VARCHAR2(50 BYTE), 
  "EMPLOYEE_POSITION" VARCHAR2(20 BYTE), 
  "ADDRESS" VARCHAR2(20 BYTE), 
  "PHONE_NUMBER" VARCHAR2(13 BYTE), 
  "PHOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "FRIDMAN" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GOODS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."GOODS" 
   (  "GOOD_ID" NUMBER(*,0), 
  "GOOD_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table GOODS_WAREHOUSE
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."GOODS_WAREHOUSE" 
   (  "ITEM_ID" NUMBER(*,0), 
  "SPECIFICATION" VARCHAR2(25 BYTE), 
  "SHIP_DATE" DATE, 
  "WAYBILL_NUM" NUMBER(*,0), 
  "GOODS_COUNT" NUMBER(*,0), 
  "GOODS_LEFT" NUMBER(*,0), 
  "PRICE" NUMBER(*,0), 
  "SUPPLIER_ID" NUMBER(*,0), 
  "GOOD_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."ORDERS" 
   (  "ORDER_ID" NUMBER(*,0), 
  "WAYBILL_NUM" NUMBER(*,0), 
  "ODER_DATE" DATE, 
  "SHIP_DATE" DATE, 
  "STATUS" VARCHAR2(50 BYTE), 
  "TOTAL_PRICE" NUMBER(*,0), 
  "CLIENT_ID" NUMBER(*,0), 
  "EMPLOYEE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table ORDERS_GOODS_WAREHOUSE
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" 
   (  "ORDER_ID" NUMBER(*,0), 
  "GOODS_WAREHOUSE_ID" NUMBER(*,0), 
  "GOOD_COUNT" NUMBER(*,0), 
  "PRICE" NUMBER(*,0), 
  "TOTAL_PRICE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."SUPPLIERS" 
   (  "SUPPLIER_ID" NUMBER(*,0), 
  "COMPANY_NAME" VARCHAR2(40 BYTE), 
  "CITY" VARCHAR2(20 BYTE), 
  "ADDRESS" VARCHAR2(60 BYTE), 
  "PHONE_NUMBER" VARCHAR2(13 BYTE), 
  "CONTACT_PERSON" VARCHAR2(28 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SYS_C007116
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SYS_C007116" ON "FRIDMAN"."CLIENTS" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SYS_C007146
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SYS_C007146" ON "FRIDMAN"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SYS_C007126
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SYS_C007126" ON "FRIDMAN"."GOODS" ("GOOD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SYS_C007136
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SYS_C007136" ON "FRIDMAN"."GOODS_WAREHOUSE" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SYS_C007154
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SYS_C007154" ON "FRIDMAN"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SYS_C007162
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SYS_C007162" ON "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" ("ORDER_ID", "GOODS_WAREHOUSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SYS_C007123
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SYS_C007123" ON "FRIDMAN"."SUPPLIERS" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."CLIENTS" ADD PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."CLIENTS" MODIFY ("CONTACT_PERSON" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CLIENTS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CLIENTS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CLIENTS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CLIENTS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CLIENTS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."EMPLOYEES" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("PHOTO" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("EMPLOYEE_POSITION" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOODS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."GOODS" ADD PRIMARY KEY ("GOOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."GOODS" MODIFY ("GOOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS" MODIFY ("GOOD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOODS_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("GOOD_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("GOODS_LEFT" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("GOODS_COUNT" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("WAYBILL_NUM" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("SHIP_DATE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("SPECIFICATION" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("SHIP_DATE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("ODER_DATE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("WAYBILL_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS_GOODS_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" ADD PRIMARY KEY ("ORDER_ID", "GOODS_WAREHOUSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" MODIFY ("GOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" MODIFY ("GOODS_WAREHOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."SUPPLIERS" ADD PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("CONTACT_PERSON" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GOODS_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" ADD CONSTRAINT "FK_GOOD_ID" FOREIGN KEY ("GOOD_ID")
    REFERENCES "FRIDMAN"."GOODS" ("GOOD_ID") ENABLE;
  ALTER TABLE "FRIDMAN"."GOODS_WAREHOUSE" ADD CONSTRAINT "FK_SUPPLIER_ID" FOREIGN KEY ("SUPPLIER_ID")
    REFERENCES "FRIDMAN"."SUPPLIERS" ("SUPPLIER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDERS" ADD CONSTRAINT "FK_EMPLOYEE_ID" FOREIGN KEY ("EMPLOYEE_ID")
    REFERENCES "FRIDMAN"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
  ALTER TABLE "FRIDMAN"."ORDERS" ADD CONSTRAINT "FK_ORDER_ID" FOREIGN KEY ("CLIENT_ID")
    REFERENCES "FRIDMAN"."CLIENTS" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS_GOODS_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" ADD FOREIGN KEY ("ORDER_ID")
    REFERENCES "FRIDMAN"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "FRIDMAN"."ORDERS_GOODS_WAREHOUSE" ADD FOREIGN KEY ("GOODS_WAREHOUSE_ID")
    REFERENCES "FRIDMAN"."GOODS_WAREHOUSE" ("ITEM_ID") ENABLE;
