--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."CUSTOMERS" 
   (  "CUSTOMER_ID" NUMBER(*,0), 
  "CITY" VARCHAR2(20 BYTE), 
  "ADDRESS" VARCHAR2(60 BYTE), 
  "COMPANY_NAME" VARCHAR2(40 BYTE), 
  "PHONE_NUMBER" VARCHAR2(13 BYTE), 
  "CONTACT_PERSON" VARCHAR2(28 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."EMPLOYEES" 
   (  "EMPLOYEE_ID" NUMBER(*,0), 
  "LAST_NAME" VARCHAR2(50 BYTE), 
  "FIRST_NAME" VARCHAR2(50 BYTE), 
  "EMPLOYEE_POSITION" VARCHAR2(20 BYTE), 
  "ADDRESS" VARCHAR2(20 BYTE), 
  "PHONE_NUMBER" VARCHAR2(13 BYTE), 
  "PHOTO" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "FRIDMAN" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ORDER_PRODUCT_WAREHOUSE
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" 
   (  "ORDER_ID" NUMBER(*,0), 
  "PRODUCT_WAREHOUSE_ID" NUMBER(*,0), 
  "PRODUCT_COUNT" NUMBER(*,0), 
  "PRICE" NUMBER(*,0), 
  "TOTAL_PRICE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."ORDERS" 
   (  "ORDER_ID" NUMBER(*,0), 
  "WAYBILL_NUM" NUMBER(*,0), 
  "ODER_DATE" DATE, 
  "SHIP_DATE" DATE, 
  "STATUS" VARCHAR2(50 BYTE), 
  "TOTAL_PRICE" NUMBER(*,0), 
  "CUSTOMER_ID" NUMBER(*,0), 
  "EMPLOYEE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_WAREHOUSE
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" 
   (  "PRODUCT_WAREHOUSE_ID" NUMBER(*,0), 
  "SPECIFICATION" VARCHAR2(25 BYTE), 
  "SHIP_DATE" DATE, 
  "WAYBILL_NUM" NUMBER(*,0), 
  "PRODUCT_COUNT" NUMBER(*,0), 
  "PRODUCT_LEFT" NUMBER(*,0), 
  "PRICE" NUMBER(*,0), 
  "SUPPLIER_ID" NUMBER(*,0), 
  "PRODUCT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."PRODUCTS" 
   (  "PRODUCT_ID" NUMBER(*,0), 
  "PRODUCT_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Table SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "FRIDMAN"."SUPPLIERS" 
   (  "SUPPLIER_ID" NUMBER(*,0), 
  "COMPANY_NAME" VARCHAR2(40 BYTE), 
  "CITY" VARCHAR2(20 BYTE), 
  "ADDRESS" VARCHAR2(60 BYTE), 
  "PHONE_NUMBER" VARCHAR2(13 BYTE), 
  "CONTACT_PERSON" VARCHAR2(28 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."CUSTOMERS_PK" ON "FRIDMAN"."CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."EMPLOYEES_PK" ON "FRIDMAN"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index ORDER_PRODUCT_WAREHOUSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE_PK" ON "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" ("ORDER_ID", "PRODUCT_WAREHOUSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."ORDERS_PK" ON "FRIDMAN"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_WAREHOUSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."PRODUCT_WAREHOUSE_PK" ON "FRIDMAN"."PRODUCT_WAREHOUSE" ("PRODUCT_WAREHOUSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."PRODUCTS_PK" ON "FRIDMAN"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  DDL for Index SUPPLIERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIDMAN"."SUPPLIERS_PK" ON "FRIDMAN"."SUPPLIERS" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."CUSTOMERS" MODIFY ("CONTACT_PERSON" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CUSTOMERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CUSTOMERS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CUSTOMERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CUSTOMERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("PHOTO" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("EMPLOYEE_POSITION" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_PRODUCT_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" ADD CONSTRAINT "ORDER_PRODUCT_WAREHOUSE_PK" PRIMARY KEY ("ORDER_ID", "PRODUCT_WAREHOUSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" MODIFY ("PRODUCT_COUNT" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" MODIFY ("PRODUCT_WAREHOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("SHIP_DATE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("ODER_DATE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("WAYBILL_NUM" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" ADD CONSTRAINT "PRODUCT_WAREHOUSE_PK" PRIMARY KEY ("PRODUCT_WAREHOUSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("PRODUCT_LEFT" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("PRODUCT_COUNT" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("WAYBILL_NUM" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("SHIP_DATE" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("SPECIFICATION" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" MODIFY ("PRODUCT_WAREHOUSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."SUPPLIERS" ADD CONSTRAINT "SUPPLIERS_PK" PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FRIDMAN"  ENABLE;
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("CONTACT_PERSON" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FRIDMAN"."SUPPLIERS" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDER_PRODUCT_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" ADD FOREIGN KEY ("ORDER_ID")
    REFERENCES "FRIDMAN"."ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "FRIDMAN"."ORDER_PRODUCT_WAREHOUSE" ADD FOREIGN KEY ("PRODUCT_WAREHOUSE_ID")
    REFERENCES "FRIDMAN"."PRODUCT_WAREHOUSE" ("PRODUCT_WAREHOUSE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."ORDERS" ADD CONSTRAINT "ORDERS_CUSTOMERS_FK" FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "FRIDMAN"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "FRIDMAN"."ORDERS" ADD CONSTRAINT "ORDERS_EMPLOYEES_FK" FOREIGN KEY ("EMPLOYEE_ID")
    REFERENCES "FRIDMAN"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT_WAREHOUSE
--------------------------------------------------------

  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" ADD CONSTRAINT "PRODUCT_WAREHOUSE_PRODUCTS_FK" FOREIGN KEY ("PRODUCT_ID")
    REFERENCES "FRIDMAN"."PRODUCTS" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "FRIDMAN"."PRODUCT_WAREHOUSE" ADD CONSTRAINT "PRODUCT_WAREHOUSE_SUPPLIERS_FK" FOREIGN KEY ("SUPPLIER_ID")
    REFERENCES "FRIDMAN"."SUPPLIERS" ("SUPPLIER_ID") ENABLE;
