--------------------------------------------------------
--  File created - Wednesday-October-07-2015   
--------------------------------------------------------
-- Unable to render TABLE DDL for object FLIGHTSLAB.CITIES with DBMS_METADATA attempting internal generator.
CREATE TABLE CITIES 
(
  CITY_ID NUMBER(*, 0) NOT NULL 
, CITY_NAME VARCHAR2(50 BYTE) 
, CONSTRAINT CITIES_PK PRIMARY KEY 
  (
    CITY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CITIES_PK ON CITIES (CITY_ID ASC) 
      LOGGING 
      TABLESPACE FLIGHTSLAB 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE FLIGHTSLAB 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
--------------------------------------------------------
--  DDL for Table COMPANIES
--------------------------------------------------------

  CREATE TABLE "FLIGHTSLAB"."COMPANIES" 
   (	"COMPANY_ID" NUMBER(*,0), 
	"COMPANY_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Table CREWS
--------------------------------------------------------

  CREATE TABLE "FLIGHTSLAB"."CREWS" 
   (	"CREW_ID" NUMBER(*,0), 
	"COMPANY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Table FLIGHT_PROTOTYPES
--------------------------------------------------------

  CREATE TABLE "FLIGHTSLAB"."FLIGHT_PROTOTYPES" 
   (	"FLIGHT_PROTOTYPE_ID" NUMBER(*,0), 
	"DEPARTURE_CITY_ID" NUMBER(*,0), 
	"ARRIVAL_CITY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Table FLIGHTS
--------------------------------------------------------

  CREATE TABLE "FLIGHTSLAB"."FLIGHTS" 
   (	"FLIGHT_ID" NUMBER(*,0), 
	"CREW_ID" NUMBER(*,0), 
	"PLANE_ID" NUMBER(*,0), 
	"FLIGHT_PROTOTYPE_ID" NUMBER(*,0), 
	"FLIGHT_STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Table PLANE_MODELS
--------------------------------------------------------

  CREATE TABLE "FLIGHTSLAB"."PLANE_MODELS" 
   (	"PLANE_MODEL_ID" NUMBER(*,0), 
	"MODEL_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Table PLANES
--------------------------------------------------------

  CREATE TABLE "FLIGHTSLAB"."PLANES" 
   (	"PLANE_ID" NUMBER(*,0), 
	"COMPANY_ID" NUMBER(*,0), 
	"PLANE_MODEL_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Index CITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHTSLAB"."CITIES_PK" ON "FLIGHTSLAB"."CITIES" ("CITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Index COMPANIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHTSLAB"."COMPANIES_PK" ON "FLIGHTSLAB"."COMPANIES" ("COMPANY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Index CREWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHTSLAB"."CREWS_PK" ON "FLIGHTSLAB"."CREWS" ("CREW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Index FLIGHT_PROTOTYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHTSLAB"."FLIGHT_PROTOTYPES_PK" ON "FLIGHTSLAB"."FLIGHT_PROTOTYPES" ("FLIGHT_PROTOTYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Index FLIGHTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHTSLAB"."FLIGHTS_PK" ON "FLIGHTSLAB"."FLIGHTS" ("FLIGHT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Index PLANE_MODELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHTSLAB"."PLANE_MODELS_PK" ON "FLIGHTSLAB"."PLANE_MODELS" ("PLANE_MODEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  DDL for Index PLANES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLIGHTSLAB"."PLANES_PK" ON "FLIGHTSLAB"."PLANES" ("PLANE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB" ;
--------------------------------------------------------
--  Constraints for Table CITIES
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."CITIES" ADD CONSTRAINT "CITIES_PK" PRIMARY KEY ("CITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPANIES
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."COMPANIES" ADD CONSTRAINT "COMPANIES_PK" PRIMARY KEY ("COMPANY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CREWS
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."CREWS" ADD CONSTRAINT "CREWS_PK" PRIMARY KEY ("CREW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FLIGHT_PROTOTYPES
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."FLIGHT_PROTOTYPES" ADD CONSTRAINT "FLIGHT_PROTOTYPES_PK" PRIMARY KEY ("FLIGHT_PROTOTYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FLIGHTS
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."FLIGHTS" ADD CONSTRAINT "FLIGHTS_PK" PRIMARY KEY ("FLIGHT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB"  ENABLE;
  ALTER TABLE "FLIGHTSLAB"."FLIGHTS" ADD CONSTRAINT "CHECK_STATUS" CHECK (flight_status IN ('in_flight','arrived','prepearing')) ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANE_MODELS
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."PLANE_MODELS" ADD CONSTRAINT "PLANE_MODELS_PK" PRIMARY KEY ("PLANE_MODEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANES
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."PLANES" ADD CONSTRAINT "PLANES_PK" PRIMARY KEY ("PLANE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FLIGHTSLAB"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CREWS
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."CREWS" ADD CONSTRAINT "CREWS_COMPANIES_FK" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "FLIGHTSLAB"."COMPANIES" ("COMPANY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLIGHT_PROTOTYPES
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."FLIGHT_PROTOTYPES" ADD CONSTRAINT "FLIGHTS_CITIES_ARRIVAL_FK" FOREIGN KEY ("ARRIVAL_CITY_ID")
	  REFERENCES "FLIGHTSLAB"."CITIES" ("CITY_ID") ENABLE;
  ALTER TABLE "FLIGHTSLAB"."FLIGHT_PROTOTYPES" ADD CONSTRAINT "FLIGHTS_CITIES_DEPARTURE_FK" FOREIGN KEY ("DEPARTURE_CITY_ID")
	  REFERENCES "FLIGHTSLAB"."CITIES" ("CITY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLIGHTS
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."FLIGHTS" ADD CONSTRAINT "FLIGHTS_CREWS_FK" FOREIGN KEY ("CREW_ID")
	  REFERENCES "FLIGHTSLAB"."CREWS" ("CREW_ID") ENABLE;
  ALTER TABLE "FLIGHTSLAB"."FLIGHTS" ADD CONSTRAINT "FLIGHTS_FLIGHT_PROTOTYPES_FK" FOREIGN KEY ("FLIGHT_PROTOTYPE_ID")
	  REFERENCES "FLIGHTSLAB"."FLIGHT_PROTOTYPES" ("FLIGHT_PROTOTYPE_ID") ENABLE;
  ALTER TABLE "FLIGHTSLAB"."FLIGHTS" ADD CONSTRAINT "FLIGHTS_PLANES_FK" FOREIGN KEY ("PLANE_ID")
	  REFERENCES "FLIGHTSLAB"."PLANES" ("PLANE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANES
--------------------------------------------------------

  ALTER TABLE "FLIGHTSLAB"."PLANES" ADD CONSTRAINT "PLANES_COMPANIES_FK" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "FLIGHTSLAB"."COMPANIES" ("COMPANY_ID") ENABLE;
  ALTER TABLE "FLIGHTSLAB"."PLANES" ADD CONSTRAINT "PLANES_PLANE_MODELS_FK" FOREIGN KEY ("PLANE_MODEL_ID")
	  REFERENCES "FLIGHTSLAB"."PLANE_MODELS" ("PLANE_MODEL_ID") ENABLE;
