-- 4.1
SELECT ORGANISATIONS.TAX_NUMBER TAX_NUMBER,
  ORGANISATIONS.ORGANISATION_NAME ORGANISATION_NAME,
  ORGANISATIONS.ADDRESS ADDRESS,
  ORGANISATIONS.PHONE PHONE
FROM ORGANISATIONS
RIGHT OUTER JOIN SUPPLIERS
ON SUPPLIERS.ORGANISATION_ID = ORGANISATIONS.ORGANISATION_ID;
-- 4.2
SELECT GOOD_NAME
FROM GOODS
WHERE NOT EXISTS
  (SELECT STOCKS.GOOD_ID FROM STOCKS WHERE STOCKS.GOOD_ID = goods.GOOD_ID
  );
-- 4.3
SELECT GOODS.GOOD_NAME
FROM GOODS
JOIN STOCKS
ON STOCKS.GOOD_ID = GOODS.GOOD_ID
GROUP BY GOODS.GOOD_NAME
HAVING SUM(STOCKS.RESIDUE) <= 100;
-- 4.4
SELECT ORDERS.ORDER_ID,
  ORDERS.INVOICE_NUMBER,
  ORDERS.ORDER_DATE
FROM ORDERS
JOIN GOODS_ORDERS
ON ORDERS.ORDER_ID = GOODS_ORDERS.ORDER_ID
GROUP BY ORDERS.ORDER_ID,
  ORDERS.INVOICE_NUMBER,
  ORDERS.ORDER_DATE
HAVING SUM(GOODS_ORDERS.AMOUNT) > 2;
-- 4.5
SELECT ORGANISATIONS.ORGANISATION_NAME
FROM CLIENTS
JOIN ORDERS
ON orders.MANAGER_CLIENT_ID = CLIENTS.MANAGER_CLIENT_ID
JOIN ORGANISATIONS
ON ORGANISATIONS.ORGANISATION_ID = CLIENTS.ORGANISATION_ID
GROUP BY CLIENTS.ORGANISATION_ID,
  ORGANISATIONS.ORGANISATION_NAME
HAVING COUNT(CLIENTS.ORGANISATION_ID) > 5;
-- 4.6
SELECT DISTINCT CLIENTS.ORGANISATION_ID
FROM CLIENTS
JOIN ORDERS
ON ORDERS.MANAGER_CLIENT_ID = CLIENTS.MANAGER_CLIENT_ID
JOIN GOODS_ORDERS
ON ORDERS.ORDER_ID          = GOODS_ORDERS.ORDER_ID
WHERE GOODS_ORDERS.STOCK_ID = 12;
-- 4.7
SELECT STOCKS.SPEC
FROM STOCKS
JOIN GOODS
ON STOCKS.GOOD_ID     = GOODS.GOOD_ID
WHERE GOODS.GOOD_NAME = 'Монитор'
AND STOCKS.RESIDUE    > 0
AND STOCKS.PRICE      =
  (SELECT MIN(PRICE)
  FROM STOCKS
  JOIN GOODS
  ON STOCKS.GOOD_ID     = GOODS.GOOD_ID
  WHERE GOODS.GOOD_NAME = 'Монитор'
  );